
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures in Code
email: samhiatt@gmail.com
description: >- 
  A space where I share my adventures in artificial intelligence and machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samhiatt.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#repository: "samhiatt/samhiatt.github.io"
#twitter_username: 

#github: [metadata]

github_username:  samhiatt
author: Sam Hiatt
author_avatar_url: /assets/images/me.jpeg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
